[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10

[nixpacks]
staticDir = "public"